---

- name: "Certificate exist for {{ item.value.domain }}"
  stat:
    path: "/etc/letsencrypt/live/{{ item.value.domain }}/fullchain.pem"
  register: fullchain

- name: Stop HAProxy
  service:
    name: haproxy
    state: stopped
  notify: Restart HAProxy
  when: not fullchain.stat.exists

- name: "generate staging ssl certificates for {{ item.value.domain }}"
  command: "certbot certonly --standalone --email {{ email }} --agree-tos -n -d {{ item.value.domain }} --staging"
  when:
    - not fullchain.stat.exists
    - item.value.letsencrypt == 'staging'

- name: "generate ssl certificates for {{ item.value.domain }}"
  command: "certbot certonly --standalone --email {{ email }} --agree-tos -n -d {{ item.value.domain }}"
  when:
    - not fullchain.stat.exists
    - item.value.letsencrypt != 'staging'

- name: Assemble certificates
  shell: "cat /etc/letsencrypt/live/{{ item.value.domain }}/privkey.pem /etc/letsencrypt/live/{{ item.value.domain }}/fullchain.pem > /etc/letsencrypt/live/{{ item.value.domain }}/privkeyandcert.pem"
  when:
    - not fullchain.stat.exists

- name: Wait before issuing next certificate
  pause:
    seconds: 5
  when:
    - not fullchain.stat.exists
